/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpack;
import com.mysql.jdbc.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import myconnector.connectors;
import static myconnector.connectors.conUrl;
/**
 *
 * @author Acer-User
 */
public class maintable extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public maintable() {
        initComponents();
         this.setLocationRelativeTo(null);
        refresh();
    }
        public maintable(String sname) {
        initComponents();
         this.setLocationRelativeTo(null);
         name.setText(sname);
        refresh();
    }
    
     Object id = null;
      //Product product_obj = new Product();
    //connectors connection = new connectors();
    
     public void clearaddprodukto(){
        pbname.setText(null);
         pmodel.setText(null);
          punit.setText(null);
        pquan.setValue(0);
        pprice.setText(null);
        pbname.requestFocus();
    }
     
      void enableAndClearFields(){
        pbname.setEnabled(true);
        pmodel.setEnabled(true);
        punit.setEnabled(true);
        pquan.setEnabled(true);
        pprice.setEnabled(true);
        clearaddprodukto();
    }

      
 public void refresh(){
        try{
            Class.forName("com.mysql.jdbc.Driver");        
         Connection con =  DriverManager.getConnection(conUrl);
            
        
         String sql = "select * from product order by id asc";
            Statement stmt = (Statement) con.prepareCall(sql);
           ResultSet rs = stmt.executeQuery(sql);
           
           
            DefaultTableModel model = (DefaultTableModel) tableproduct.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id"),rs.getString("brand"),rs.getString("model"),rs.getString("unit"),rs.getString("quantity"),rs.getString("price")});
                
            }
            
       
    } catch (ClassNotFoundException ex) {
            Logger.getLogger(maintable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(maintable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
 
 
   final void search(String keyword) {
        try {
            Class.forName("com.mysql.jdbc.Driver");        
         Connection con =  DriverManager.getConnection(conUrl);

            String sql = "SELECT * FROM product WHERE id LIKE ? OR brand LIKE ? ";
            PreparedStatement pstmt = (PreparedStatement) con.prepareStatement(sql);

            pstmt.setString(1, "%" + keyword + "%");
            pstmt.setString(2, "%" + keyword + "%");
            
            ResultSet rs = pstmt.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) tableproduct.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("id"), rs.getString("brand"), rs.getString("model"), rs.getString("unit"), rs.getString("quantity"), rs.getString("price")});
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(maintable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(maintable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    

    
                     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addprodukto = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        pbname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pmodel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        punit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pquan = new javax.swing.JSpinner();
        pprice = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        addb = new javax.swing.JButton();
        addq = new javax.swing.JButton();
        saveb = new javax.swing.JButton();
        exquan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduct = new javax.swing.JTable();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addqauntity = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        keywordsearch = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();

        addprodukto.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Brand Name:");

        jLabel2.setText("Model:");

        jLabel3.setText("Unit:");

        jLabel4.setText("Quantity:");

        pquan.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        pprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        pprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppriceActionPerformed(evt);
            }
        });

        jLabel5.setText("Price:");

        addb.setText("Add");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        addq.setText("Add Quantity");
        addq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addqActionPerformed(evt);
            }
        });

        saveb.setText("Save");
        saveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addproduktoLayout = new javax.swing.GroupLayout(addprodukto.getContentPane());
        addprodukto.getContentPane().setLayout(addproduktoLayout);
        addproduktoLayout.setHorizontalGroup(
            addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addproduktoLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addproduktoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(pmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addproduktoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(pbname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addproduktoLayout.createSequentialGroup()
                        .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exquan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pquan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(punit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pprice, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addproduktoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
        );
        addproduktoLayout.setVerticalGroup(
            addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addproduktoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pbname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(punit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pquan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addproduktoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exquan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addproduktoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pprice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(62, 62, 62)
                .addComponent(addb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveb)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Brand Name", "Model", "Unit", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproduct.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableproduct);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("EDIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        addqauntity.setText("ADD QUANTITY");
        addqauntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addqauntityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addqauntity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(addqauntity)
                .addGap(32, 32, 32))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel3);

        keywordsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordsearchActionPerformed(evt);
            }
        });
        keywordsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordsearchKeyReleased(evt);
            }
        });

        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        name.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(keywordsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn)
                    .addComponent(name))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  addprodukto.setVisible(true);
  addprodukto.setAlwaysOnTop(true);
  addprodukto.setLocationRelativeTo(null);
  saveb.setVisible(false);
  addb.setVisible(true);
  addq.setVisible(false);
  this.enableAndClearFields();
  
  
        //addprodukto.setAlwaysOnTop(true);
                                          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ppriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppriceActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
   Product product_obj = new Product();
        String pb = pbname.getText();
    String pm = pmodel.getText();
     String pu = punit.getText();
        int qty = Integer.parseInt(pquan.getValue().toString());
        float price = Float.parseFloat(pprice.getValue().toString());
        //float price = Float.parseFloat(proprice.getValue().toString());
        //System.out.println(price);
        int r = product_obj.addProduct(pb,pm, pu, qty, price);
        if(r==1){
            JOptionPane.showMessageDialog(addprodukto, "New Product Added Successfully");
            clearaddprodukto();
          
            refresh();        // TODO add your handling code here:
    }//GEN-LAST:event_addbActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  Product product_obj = new Product();
        int r = tableproduct.getSelectedRow();
        
        if(r == -1){
            JOptionPane.showMessageDialog(rootPane, "Please select a row","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            Object id = tableproduct.getValueAt(r, 0);
            Object product_name = tableproduct.getValueAt(r, 1);
            int c = JOptionPane.showConfirmDialog(rootPane, "This will delete "+product_name+".\nClick OK to continue","Confirm Delete",JOptionPane.OK_CANCEL_OPTION);
            
            if(c==JOptionPane.OK_OPTION){
                int cc = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete "+product_name+"?", "Delete", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                if(cc == JOptionPane.YES_OPTION){
                    int re = product_obj.deleteProduct(id);
                    if(re == 1){
                        JOptionPane.showMessageDialog(rootPane, "Product "+product_name+" deleted!","Product Deleted",JOptionPane.WARNING_MESSAGE);
                        refresh();
                    }
                }
            }  
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
          // TODO add your handling code here:
        String keyword = keywordsearch.getText();
        this.search(keyword);
    }//GEN-LAST:event_searchbtnActionPerformed

    private void keywordsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordsearchKeyReleased
        // TODO add your handling code here:
          String keyword = keywordsearch.getText();
        this.search(keyword);
    }//GEN-LAST:event_keywordsearchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        this.enableAndClearFields();
        int row = tableproduct.getSelectedRow();

        if (row != -1) {
            addprodukto.setVisible(true);
            addprodukto.setAlwaysOnTop(true);
            addprodukto.setLocationRelativeTo(null);
            addb.setVisible(false);
            saveb.setVisible(true);
            addq.setVisible(false);
            pquan.setEnabled(false);

            id = tableproduct.getValueAt(row, 0);
            Object pname = tableproduct.getValueAt(row, 1);
            Object pmod = tableproduct.getValueAt(row, 2);
            Object puni = tableproduct.getValueAt(row, 3);            
            Object pqty = tableproduct.getValueAt(row, 4);
            Object price = tableproduct.getValueAt(row, 5);

            pbname.setText((String) pname);
            pmodel.setText((String) pmod);
            punit.setText((String) puni);
            pquan.setValue(Integer.valueOf(pqty.toString()));
            pprice.setValue(Float.valueOf(price.toString()));

        } else {
            JOptionPane.showMessageDialog(rootPane, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }


       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    private void addqauntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addqauntityActionPerformed
        // TODO add your handling code here:
           this.enableAndClearFields();
           int row = tableproduct.getSelectedRow();
           if(row != -1){
                addprodukto.setVisible(true);
                addprodukto.setAlwaysOnTop(true);
                addprodukto.setLocationRelativeTo(this);
                addb.setVisible(false);
                saveb.setVisible(false);
                addq.setVisible(true);
                
                id = tableproduct.getValueAt(row, 0);
                Object pn = tableproduct.getValueAt(row, 1);
                Object pmod = tableproduct.getValueAt(row, 2);
                Object puni = tableproduct.getValueAt(row, 3);
                Object qt = tableproduct.getValueAt(row, 4);
                Object pr = tableproduct.getValueAt(row, 5);
                
                pbname.setText(pn.toString());
                exquan.setText(qt.toString());
                pprice.setValue(Double.valueOf(pr.toString()));
                
                pbname.setEnabled(false);
                pmodel.setEnabled(false);
                punit.setEnabled(false);
                pprice.setEnabled(false);
                
                
           }else{
               JOptionPane.showMessageDialog(rootPane, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
           }
        
        
    }//GEN-LAST:event_addqauntityActionPerformed

    private void addqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addqActionPerformed
        // TODO add your handling code here:
       Product product_obj = new Product();
        Object pn = pbname.getText();
        Object qty = pquan.getValue();
        int c = JOptionPane.showConfirmDialog(addprodukto, "Would you like to add\n"+qty+ "\nto the product\n"+pn+"?", "Add Quantity", JOptionPane.YES_NO_OPTION);
        if(c==JOptionPane.YES_OPTION){
            int r = product_obj.addQuantity(id, qty);
            if(r==1){
                JOptionPane.showMessageDialog(addprodukto, "Product Quantity Updated!");
                addprodukto.setVisible(false);
                this.refresh();
            }else{
                JOptionPane.showMessageDialog(addprodukto, "Problem Updating a product", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
                                             

        
        
    }//GEN-LAST:event_addqActionPerformed

    private void keywordsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordsearchActionPerformed

    private void savebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebActionPerformed
        // TODO add your handling code here:
              Product product_obj = new Product();
           String name = pbname.getText();
           String model = pmodel.getText();
           String unit = punit.getText();
        Object price = pprice.getValue();

        int r = product_obj.editProduct(id, name,model, unit, price);
        if (r == 1) {
            JOptionPane.showMessageDialog(addprodukto, "Product Edited");
            addprodukto.setVisible(false);
            this.refresh();
        } else {
            JOptionPane.showMessageDialog(addprodukto, "Problem Editing a product", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_savebActionPerformed
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maintable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maintable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maintable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maintable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maintable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JFrame addprodukto;
    private javax.swing.JButton addq;
    private javax.swing.JButton addqauntity;
    private javax.swing.JLabel exquan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField keywordsearch;
    private javax.swing.JLabel name;
    private javax.swing.JTextField pbname;
    private javax.swing.JTextField pmodel;
    private javax.swing.JFormattedTextField pprice;
    private javax.swing.JSpinner pquan;
    private javax.swing.JTextField punit;
    private javax.swing.JButton saveb;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable tableproduct;
    // End of variables declaration//GEN-END:variables
//To change body of generated methods, choose Tools | Templates.
    }
        


